/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddressDTO model module.
 * @module model/AddressDTO
 * @version v1.0.0
 */
class AddressDTO {
    /**
     * Constructs a new <code>AddressDTO</code>.
     * @alias module:model/AddressDTO
     */
    constructor() { 
        
        AddressDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddressDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressDTO} obj Optional instance to populate.
     * @return {module:model/AddressDTO} The populated <code>AddressDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressDTO();

            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
            if (data.hasOwnProperty('line2')) {
                obj['line2'] = ApiClient.convertToType(data['line2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('zipCode')) {
                obj['zipCode'] = ApiClient.convertToType(data['zipCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} line1
 */
AddressDTO.prototype['line1'] = undefined;

/**
 * @member {String} line2
 */
AddressDTO.prototype['line2'] = undefined;

/**
 * @member {String} city
 */
AddressDTO.prototype['city'] = undefined;

/**
 * @member {String} state
 */
AddressDTO.prototype['state'] = undefined;

/**
 * @member {String} country
 */
AddressDTO.prototype['country'] = undefined;

/**
 * @member {String} zipCode
 */
AddressDTO.prototype['zipCode'] = undefined;






export default AddressDTO;

