/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomAttributeDTO model module.
 * @module model/CustomAttributeDTO
 * @version v1.0.0
 */
class CustomAttributeDTO {
    /**
     * Constructs a new <code>CustomAttributeDTO</code>.
     * @alias module:model/CustomAttributeDTO
     * @param customAttributeName {String} 
     */
    constructor(customAttributeName) { 
        
        CustomAttributeDTO.initialize(this, customAttributeName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customAttributeName) { 
        obj['customAttributeName'] = customAttributeName;
    }

    /**
     * Constructs a <code>CustomAttributeDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttributeDTO} obj Optional instance to populate.
     * @return {module:model/CustomAttributeDTO} The populated <code>CustomAttributeDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttributeDTO();

            if (data.hasOwnProperty('customAttributeId')) {
                obj['customAttributeId'] = ApiClient.convertToType(data['customAttributeId'], 'Number');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = ApiClient.convertToType(data['entityType'], 'String');
            }
            if (data.hasOwnProperty('toolId')) {
                obj['toolId'] = ApiClient.convertToType(data['toolId'], 'Number');
            }
            if (data.hasOwnProperty('customAttributeName')) {
                obj['customAttributeName'] = ApiClient.convertToType(data['customAttributeName'], 'String');
            }
            if (data.hasOwnProperty('attributeType')) {
                obj['attributeType'] = ApiClient.convertToType(data['attributeType'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], ['String']);
            }
            if (data.hasOwnProperty('checked')) {
                obj['checked'] = ApiClient.convertToType(data['checked'], 'Boolean');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} customAttributeId
 */
CustomAttributeDTO.prototype['customAttributeId'] = undefined;

/**
 * @member {String} entityType
 */
CustomAttributeDTO.prototype['entityType'] = undefined;

/**
 * @member {Number} toolId
 */
CustomAttributeDTO.prototype['toolId'] = undefined;

/**
 * @member {String} customAttributeName
 */
CustomAttributeDTO.prototype['customAttributeName'] = undefined;

/**
 * @member {String} attributeType
 */
CustomAttributeDTO.prototype['attributeType'] = undefined;

/**
 * @member {Array.<String>} options
 */
CustomAttributeDTO.prototype['options'] = undefined;

/**
 * @member {Boolean} checked
 */
CustomAttributeDTO.prototype['checked'] = undefined;

/**
 * @member {Boolean} required
 */
CustomAttributeDTO.prototype['required'] = undefined;






export default CustomAttributeDTO;

