/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerDTO model module.
 * @module model/CustomerDTO
 * @version v1.0.0
 */
class CustomerDTO {
    /**
     * Constructs a new <code>CustomerDTO</code>.
     * @alias module:model/CustomerDTO
     */
    constructor() { 
        
        CustomerDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerDTO} obj Optional instance to populate.
     * @return {module:model/CustomerDTO} The populated <code>CustomerDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerDTO();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * customer name
 * @member {String} name
 */
CustomerDTO.prototype['name'] = undefined;

/**
 * customer phone
 * @member {String} phone
 */
CustomerDTO.prototype['phone'] = undefined;

/**
 * customer email
 * @member {String} email
 */
CustomerDTO.prototype['email'] = undefined;






export default CustomerDTO;

