/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReminderDTO model module.
 * @module model/ReminderDTO
 * @version v1.0.0
 */
class ReminderDTO {
    /**
     * Constructs a new <code>ReminderDTO</code>.
     * @alias module:model/ReminderDTO
     */
    constructor() { 
        
        ReminderDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReminderDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReminderDTO} obj Optional instance to populate.
     * @return {module:model/ReminderDTO} The populated <code>ReminderDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReminderDTO();

            if (data.hasOwnProperty('reminderType')) {
                obj['reminderType'] = ApiClient.convertToType(data['reminderType'], 'Number');
            }
            if (data.hasOwnProperty('schedulingInterval')) {
                obj['schedulingInterval'] = ApiClient.convertToType(data['schedulingInterval'], 'Number');
            }
            if (data.hasOwnProperty('timeUnit')) {
                obj['timeUnit'] = ApiClient.convertToType(data['timeUnit'], 'Number');
            }
            if (data.hasOwnProperty('modes')) {
                obj['modes'] = ApiClient.convertToType(data['modes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} reminderType
 */
ReminderDTO.prototype['reminderType'] = undefined;

/**
 * @member {Number} schedulingInterval
 */
ReminderDTO.prototype['schedulingInterval'] = undefined;

/**
 * @member {Number} timeUnit
 */
ReminderDTO.prototype['timeUnit'] = undefined;

/**
 * @member {Array.<String>} modes
 */
ReminderDTO.prototype['modes'] = undefined;






export default ReminderDTO;

