/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StaticFieldDTO model module.
 * @module model/StaticFieldDTO
 * @version v1.0.0
 */
class StaticFieldDTO {
    /**
     * Constructs a new <code>StaticFieldDTO</code>.
     * @alias module:model/StaticFieldDTO
     */
    constructor() { 
        
        StaticFieldDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StaticFieldDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StaticFieldDTO} obj Optional instance to populate.
     * @return {module:model/StaticFieldDTO} The populated <code>StaticFieldDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StaticFieldDTO();

            if (data.hasOwnProperty('termsAndConditions')) {
                obj['termsAndConditions'] = ApiClient.convertToType(data['termsAndConditions'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} termsAndConditions
 */
StaticFieldDTO.prototype['termsAndConditions'] = undefined;

/**
 * @member {String} notes
 */
StaticFieldDTO.prototype['notes'] = undefined;






export default StaticFieldDTO;

