/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StaticFieldDTO from './StaticFieldDTO';

/**
 * The StatusOrExpiryDTO model module.
 * @module model/StatusOrExpiryDTO
 * @version v1.0.0
 */
class StatusOrExpiryDTO {
    /**
     * Constructs a new <code>StatusOrExpiryDTO</code>.
     * @alias module:model/StatusOrExpiryDTO
     */
    constructor() { 
        
        StatusOrExpiryDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatusOrExpiryDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusOrExpiryDTO} obj Optional instance to populate.
     * @return {module:model/StatusOrExpiryDTO} The populated <code>StatusOrExpiryDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusOrExpiryDTO();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('expiry')) {
                obj['expiry'] = ApiClient.convertToType(data['expiry'], 'String');
            }
            if (data.hasOwnProperty('staticFields')) {
                obj['staticFields'] = StaticFieldDTO.constructFromObject(data['staticFields']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} active
 */
StatusOrExpiryDTO.prototype['active'] = undefined;

/**
 * @member {String} expiry
 */
StatusOrExpiryDTO.prototype['expiry'] = undefined;

/**
 * @member {module:model/StaticFieldDTO} staticFields
 */
StatusOrExpiryDTO.prototype['staticFields'] = undefined;






export default StatusOrExpiryDTO;

