/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UdfDTO model module.
 * @module model/UdfDTO
 * @version v1.0.0
 */
class UdfDTO {
    /**
     * Constructs a new <code>UdfDTO</code>.
     * @alias module:model/UdfDTO
     */
    constructor() { 
        
        UdfDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UdfDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UdfDTO} obj Optional instance to populate.
     * @return {module:model/UdfDTO} The populated <code>UdfDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UdfDTO();

            if (data.hasOwnProperty('udf1')) {
                obj['udf1'] = ApiClient.convertToType(data['udf1'], 'String');
            }
            if (data.hasOwnProperty('udf2')) {
                obj['udf2'] = ApiClient.convertToType(data['udf2'], 'String');
            }
            if (data.hasOwnProperty('udf3')) {
                obj['udf3'] = ApiClient.convertToType(data['udf3'], 'String');
            }
            if (data.hasOwnProperty('udf4')) {
                obj['udf4'] = ApiClient.convertToType(data['udf4'], 'String');
            }
            if (data.hasOwnProperty('udf5')) {
                obj['udf5'] = ApiClient.convertToType(data['udf5'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} udf1
 */
UdfDTO.prototype['udf1'] = undefined;

/**
 * @member {String} udf2
 */
UdfDTO.prototype['udf2'] = undefined;

/**
 * @member {String} udf3
 */
UdfDTO.prototype['udf3'] = undefined;

/**
 * @member {String} udf4
 */
UdfDTO.prototype['udf4'] = undefined;

/**
 * @member {String} udf5
 */
UdfDTO.prototype['udf5'] = undefined;






export default UdfDTO;

