/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClientTokenDTO from '../model/ClientTokenDTO';

/**
* Token service.
* @module api/TokenApi
* @version v1.0.0
*/
export default class TokenApi {

    /**
    * Constructs a new TokenApi. 
    * @alias module:api/TokenApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getToken operation.
     * @callback module:api/TokenApi~getTokenCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Token
     * Get token
     * @param {String} mid merchant identifier
     * @param {module:model/ClientTokenDTO} clientTokenDTO 
     * @param {module:api/TokenApi~getTokenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getToken(mid, clientTokenDTO, callback) {
      let postBody = clientTokenDTO;
      // verify the required parameter 'mid' is set
      if (mid === undefined || mid === null) {
        throw new Error("Missing the required parameter 'mid' when calling getToken");
      }
      // verify the required parameter 'clientTokenDTO' is set
      if (clientTokenDTO === undefined || clientTokenDTO === null) {
        throw new Error("Missing the required parameter 'clientTokenDTO' when calling getToken");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'mid': mid
      };
      let formParams = {
      };

      let authNames = ['OAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
