/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HubToken);
  }
}(this, function(expect, HubToken) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HubToken.ClientTokenDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClientTokenDTO', function() {
    it('should create an instance of ClientTokenDTO', function() {
      // uncomment below and update the code to test ClientTokenDTO
      //var instane = new HubToken.ClientTokenDTO();
      //expect(instance).to.be.a(HubToken.ClientTokenDTO);
    });

    it('should have the property clientId (base name: "client_id")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new HubToken.ClientTokenDTO();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "client_secret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instance = new HubToken.ClientTokenDTO();
      //expect(instance).to.be();
    });

    it('should have the property grantType (base name: "grant_type")', function() {
      // uncomment below and update the code to test the property grantType
      //var instance = new HubToken.ClientTokenDTO();
      //expect(instance).to.be();
    });

    it('should have the property scopes (base name: "scopes")', function() {
      // uncomment below and update the code to test the property scopes
      //var instance = new HubToken.ClientTokenDTO();
      //expect(instance).to.be();
    });

  });

}));
