/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HubToken);
  }
}(this, function(expect, HubToken) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HubToken.CustomAttributeDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomAttributeDTO', function() {
    it('should create an instance of CustomAttributeDTO', function() {
      // uncomment below and update the code to test CustomAttributeDTO
      //var instane = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be.a(HubToken.CustomAttributeDTO);
    });

    it('should have the property customAttributeId (base name: "customAttributeId")', function() {
      // uncomment below and update the code to test the property customAttributeId
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property entityType (base name: "entityType")', function() {
      // uncomment below and update the code to test the property entityType
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property toolId (base name: "toolId")', function() {
      // uncomment below and update the code to test the property toolId
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property customAttributeName (base name: "customAttributeName")', function() {
      // uncomment below and update the code to test the property customAttributeName
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property attributeType (base name: "attributeType")', function() {
      // uncomment below and update the code to test the property attributeType
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property checked (base name: "checked")', function() {
      // uncomment below and update the code to test the property checked
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instance = new HubToken.CustomAttributeDTO();
      //expect(instance).to.be();
    });

  });

}));
