/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HubToken);
  }
}(this, function(expect, HubToken) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HubToken.UdfDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UdfDTO', function() {
    it('should create an instance of UdfDTO', function() {
      // uncomment below and update the code to test UdfDTO
      //var instane = new HubToken.UdfDTO();
      //expect(instance).to.be.a(HubToken.UdfDTO);
    });

    it('should have the property udf1 (base name: "udf1")', function() {
      // uncomment below and update the code to test the property udf1
      //var instance = new HubToken.UdfDTO();
      //expect(instance).to.be();
    });

    it('should have the property udf2 (base name: "udf2")', function() {
      // uncomment below and update the code to test the property udf2
      //var instance = new HubToken.UdfDTO();
      //expect(instance).to.be();
    });

    it('should have the property udf3 (base name: "udf3")', function() {
      // uncomment below and update the code to test the property udf3
      //var instance = new HubToken.UdfDTO();
      //expect(instance).to.be();
    });

    it('should have the property udf4 (base name: "udf4")', function() {
      // uncomment below and update the code to test the property udf4
      //var instance = new HubToken.UdfDTO();
      //expect(instance).to.be();
    });

    it('should have the property udf5 (base name: "udf5")', function() {
      // uncomment below and update the code to test the property udf5
      //var instance = new HubToken.UdfDTO();
      //expect(instance).to.be();
    });

  });

}));
