/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddressDTO from './model/AddressDTO';
import ClientTokenDTO from './model/ClientTokenDTO';
import CustomAttributeDTO from './model/CustomAttributeDTO';
import CustomerDTO from './model/CustomerDTO';
import PaymentLinkRequestDTO from './model/PaymentLinkRequestDTO';
import ReminderDTO from './model/ReminderDTO';
import ResultDTO from './model/ResultDTO';
import StaticFieldDTO from './model/StaticFieldDTO';
import StatusOrExpiryDTO from './model/StatusOrExpiryDTO';
import UdfDTO from './model/UdfDTO';
import PaymentLinkApi from './api/PaymentLinkApi';
import TokenApi from './api/TokenApi';


/**
* Generate_Token.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HubToken = require('index'); // See note below*.
* var xxxSvc = new HubToken.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HubToken.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HubToken.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HubToken.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddressDTO model constructor.
     * @property {module:model/AddressDTO}
     */
    AddressDTO,

    /**
     * The ClientTokenDTO model constructor.
     * @property {module:model/ClientTokenDTO}
     */
    ClientTokenDTO,

    /**
     * The CustomAttributeDTO model constructor.
     * @property {module:model/CustomAttributeDTO}
     */
    CustomAttributeDTO,

    /**
     * The CustomerDTO model constructor.
     * @property {module:model/CustomerDTO}
     */
    CustomerDTO,

    /**
     * The PaymentLinkRequestDTO model constructor.
     * @property {module:model/PaymentLinkRequestDTO}
     */
    PaymentLinkRequestDTO,

    /**
     * The ReminderDTO model constructor.
     * @property {module:model/ReminderDTO}
     */
    ReminderDTO,

    /**
     * The ResultDTO model constructor.
     * @property {module:model/ResultDTO}
     */
    ResultDTO,

    /**
     * The StaticFieldDTO model constructor.
     * @property {module:model/StaticFieldDTO}
     */
    StaticFieldDTO,

    /**
     * The StatusOrExpiryDTO model constructor.
     * @property {module:model/StatusOrExpiryDTO}
     */
    StatusOrExpiryDTO,

    /**
     * The UdfDTO model constructor.
     * @property {module:model/UdfDTO}
     */
    UdfDTO,

    /**
    * The PaymentLinkApi service constructor.
    * @property {module:api/PaymentLinkApi}
    */
    PaymentLinkApi,

    /**
    * The TokenApi service constructor.
    * @property {module:api/TokenApi}
    */
    TokenApi
};
