/**
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HubToken);
  }
}(this, function(expect, HubToken) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HubToken.PaymentLinkApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentLinkApi', function() {
    describe('changeStatusOrExpiry', function() {
      it('should call changeStatusOrExpiry successfully', function(done) {
        //uncomment below and update the code to test changeStatusOrExpiry
        //instance.changeStatusOrExpiry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPaymentLink', function() {
      it('should call createPaymentLink successfully', function(done) {
        //uncomment below and update the code to test createPaymentLink
        //instance.createPaymentLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllPaymentLink', function() {
      it('should call getAllPaymentLink successfully', function(done) {
        //uncomment below and update the code to test getAllPaymentLink
        //instance.getAllPaymentLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMerchantCustomAttributes', function() {
      it('should call getMerchantCustomAttributes successfully', function(done) {
        //uncomment below and update the code to test getMerchantCustomAttributes
        //instance.getMerchantCustomAttributes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPaymentLinkTransactions', function() {
      it('should call getPaymentLinkTransactions successfully', function(done) {
        //uncomment below and update the code to test getPaymentLinkTransactions
        //instance.getPaymentLinkTransactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSinglePaymentLink', function() {
      it('should call getSinglePaymentLink successfully', function(done) {
        //uncomment below and update the code to test getSinglePaymentLink
        //instance.getSinglePaymentLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendPaymentLink', function() {
      it('should call sendPaymentLink successfully', function(done) {
        //uncomment below and update the code to test sendPaymentLink
        //instance.sendPaymentLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('summary', function() {
      it('should call summary successfully', function(done) {
        //uncomment below and update the code to test summary
        //instance.summary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
